version: "3.7"
services:
  api:
    build: ./api
    image: movie-recommender-api
    ports:
      - "8999:80"
    env_file:
      - api/env/solr-docker-compose.env
      - api/env/redis-docker-compose.env
  batch:
    build: ./batch
    image: ml-playground-batch
    env_file:
      - batch/env/core.env
      - batch/env/input_db-docker-compose.env
      - batch/env/redis-docker-compose.env
      - batch/env/solr-docker-compose.env
      - batch/env/tmdb.env
  solr:
    image: solr:8.7.0
    ports:
      - "8983:8983"
    volumes:
      - ./solr/data:/var/solr
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - movies
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./rdb/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./rdb/mysql_data:/var/lib/mysql
      # 設定ファイルをマウント
      - ./rdb/mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
  redis:
    image: redis:6.0
    ports:
      - "6379:6379"
    volumes:
      - ./redis/data:/data
    command: redis-server --appendonly yes
