version: "3.7"
services:
  api:
    build: ./api
    image: movie-recommender-api
    ports:
      - "8000:8000"
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./rdb/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./rdb/mysql_data:/var/lib/mysql
      # 設定ファイルをマウント
      - ./rdb/mysql_conf/:/etc/mysql/conf.d
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: test
