name: CI Pipeline for API

# apiディレクトリ配下のコードの変更がdevelopブランチにプッシュされたら実行
on:
  push:
    branches:
      - develop
    paths:
      - api/**
      - .github/workflows/api_ci.yaml

jobs:
  check:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        working-directory: ./api
        run: poetry install
      - name: flake8
        working-directory: ./api
        run: poetry run flake8 app --ignore E501
      - name: Check mypy
        working-directory: ./api
        run: poetry run mypy app --ignore-missing-imports --show-column-numbers --check-untyped-defs
      - name: Unit test
        working-directory: ./api
        run: poetry run pytest tests -v --cov=app
        env:
          REDIS_PROTOCOL: http
          REDIS_HOST: localhost
          REDIS_PORT: 6379
