name: CD Pipeline for API

# apiディレクトリ配下のコードの変更がdevelopブランチにプッシュされたら実行
on:
  push:
    branches:
      - develop
    paths:
      - api/**
      - .github/workflows/api_cd.yaml

jobs:
  check:
    name: Build Container
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_DEVOPS_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info
      - name: Docker Build
        run: docker build -t ml_pipeline/core_api:dev ./api
