name: CI Pipeline for Batch

# batchディレクトリ配下のコードの変更がdevelopブランチにプッシュされたら実行
on:
  push:
    branches:
      - develop
    paths:
      - batch/**
      - .github/workflows/batch_ci.yaml

jobs:
  check:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install Poetry
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
      - name: Add path for Poetry
        run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      - name: Install Dependencies
        working-directory: ./backend
        run: poetry install
      - name: flake8
        working-directory: ./backend
        run: flake8 app --ignore E501,E128
