name: CI Pipeline for FE

# feディレクトリ配下のコードの変更がdevelopブランチにプッシュされたら実行
on:
  push:
    branches:
      - develop
    paths:
      - fe/**
      - .github/workflows/fe_ci.yaml

jobs:
  check:
    name: Check the source code
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install package
        working-directory: ./fe
        run: npm install
      - name: Eslint
        run: npm run lint
