name: Push Image

on:
  push:
    branches:
      - develop
    paths:
      - ml-pipeline/**
      - .github/workflows/ml_ci.yaml

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT_ID }}
  GCP_REGION: ${{ secrets.GCP_REGION }}
  IMAGE: asia.gcr.io/${{ secrets.GCP_PROJECT_ID }}/ml-pipeline/stg:${{ github.sha }}

jobs:
  push:
    name: Push to GCR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: release
      - name: Setup GCP
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_DEVOPS_SA_KEY }}
          export_default_credentials: true
      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet
      - name: Build Image
        run: docker build -t $IMAGE ./ml-pipeline/movie-recommeder-ml-pipeline
      - name: Push Image
        run: docker push $IMAGE
